CREATE TABLE PLAYER (
    ID       UUID   PRIMARY KEY DEFAULT gen_random_uuid(),
    USERNAME TEXT   NOT NULL UNIQUE,
    PASSWORD TEXT   NOT NULL,
    ROLE     INT    NOT NULL    DEFAULT 1,
    MONEY    INT    NOT NULL    DEFAULT 20,
    NAME     TEXT,
    BIO      TEXT,
    IMAGE    TEXT,
    ELO      INT    NOT NULL    DEFAULT 100
);

CREATE TABLE CARD (
    ID           UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME         TEXT    NOT NULL,
    ELEMENT_TYPE INTEGER NOT NULL,
    DAMAGE       DECIMAL NOT NULL,
    CARD_TYPE    INTEGER NOT NULL,
    PACKAGE_ID   UUID,
    PLAYER_ID    UUID,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID)
);

CREATE TABLE DECK (
    ID        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    PLAYER_ID UUID NOT NULL,
    CARD_1_ID UUID NOT NULL,
    CARD_2_ID UUID NOT NULL,
    CARD_3_ID UUID NOT NULL,
    CARD_4_ID UUID NOT NULL,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID)
);

CREATE TABLE TRADE (
    ID             UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    PLAYER_ID      UUID    NOT NULL,
    CARD_ID        UUID    NOT NULL,
    CARD_TYPE      INTEGER NOT NULL,
    MINIMUM_DAMAGE DECIMAL NOT NULL,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID),
    FOREIGN KEY (CARD_ID)   REFERENCES CARD   (ID)
);

CREATE TABLE BATTLE (
    ID         UUID      PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_1_ID  UUID,
    USER_2_ID  UUID,
    STATUS     INTEGER   NOT NULL    DEFAULT 0,
    CREATION   TIMESTAMP NOT NULL    DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_1_ID) REFERENCES PLAYER (ID),
    FOREIGN KEY (USER_2_ID) REFERENCES PLAYER (ID)
);
